package com.myspace.azurepoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class address implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public address() {
    }




}