package com.myspace.azurepoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class bankDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("bankName")
	private java.lang.String bankName;
	@org.kie.api.definition.type.Label("bankLocation")
	private java.lang.String bankLocation;
	@org.kie.api.definition.type.Label("country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label("streetName")
	private java.lang.String streetName;

	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;

	@org.kie.api.definition.type.Label(value = "bankBranch")
	private java.lang.String bankBranch;

	@org.kie.api.definition.type.Label(value = "branchCode")
	private java.lang.String branchCode;

	public bankDetails() {
	}

	public java.lang.String getBankName() {
		return this.bankName;
	}

	public void setBankName(java.lang.String bankName) {
		this.bankName = bankName;
	}

	public java.lang.String getBankLocation() {
		return this.bankLocation;
	}

	public void setBankLocation(java.lang.String bankLocation) {
		this.bankLocation = bankLocation;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(java.lang.String streetName) {
		this.streetName = streetName;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(java.lang.String bankBranch) {
		this.bankBranch = bankBranch;
	}

	public java.lang.String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(java.lang.String branchCode) {
		this.branchCode = branchCode;
	}

	public bankDetails(java.lang.String bankName,
			java.lang.String bankLocation, java.lang.String country,
			java.lang.String streetName, java.lang.String contactNumber,
			java.lang.String bankBranch, java.lang.String branchCode) {
		this.bankName = bankName;
		this.bankLocation = bankLocation;
		this.country = country;
		this.streetName = streetName;
		this.contactNumber = contactNumber;
		this.bankBranch = bankBranch;
		this.branchCode = branchCode;
	}

}